### ISSUE TITLE
Add source to the repo

### ISSUE THREAD

**Issue by tiesmaster** [benaadams/Ben.Demystifier#5]
Please provide the source in this repository. Looking at the readme, this thing would be really valuable to already use. Good stuff building this 🥇 .

I can imagine that this is still very much in flux, and rough around the edges, but this thing would already be a great help to understand some weird stacktraces that I see every day. So I would be fine with something that not really finished yet (I'll get it to work).

If there could be a way for already using this, I'd greatly appreciate it. 🎉

**Comment by benaadams** [comment]
API still needs some work

Have been ironing out the corner cases in the stack trace; hopefully got everything. Changes
```
System.Exception: Collection was modified; enumeration operation may not execute. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Program.<Iterator>d__7.MoveNext() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 65
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Program.GenericClass`1.GenericMethod[TSubType](TSubType& value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 172
   --- End of inner exception stack trace ---
   at Program.GenericClass`1.GenericMethod[TSubType](TSubType& value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 176
   at Program.<MethodAsync>d__8.MoveNext() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<MethodAsync>d__9`1.MoveNext() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<>c__DisplayClass12_0.<Method>b__0() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 103
   at Program.<>c__DisplayClass12_0.<Method>b__1() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 105
   at Program.RunLambda(Func`1 lambda) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 97
   at Program.Method(String value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 105
   at Program.<RefMethod>g__LocalFuncRefReturn|14_1(<>c__DisplayClass14_0& ) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 127
   at Program.<RefMethod>g__LocalFuncParam|14_0(String val, <>c__DisplayClass14_0& ) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 121
   at Program.RefMethod(String value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 117
   at Program.<>c.<.cctor>b__19_1(String s, Boolean b) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 43
   at Program.<>c.<.cctor>b__19_0(String s, Boolean b) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 42
   at Program.Start(ValueTuple`2 param) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 158
   at Program.<Start>g__LocalFunc1|15_0(Int64 l) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 139
   at Program.<Start>g__LocalFunc2|15_1(Boolean b1, Boolean b2) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 144
   at Program.Start() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 135
   at Program.<>c.<.ctor>b__5_0() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 50
   at Program.<>c__DisplayClass6_0.<.ctor>b__1(Object s) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 58
   at Program.<>c.<.ctor>b__6_2(Action`1 lambda, Object state) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 45
   at Program.<>c__DisplayClass6_0.<.ctor>b__0(Object state) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 58
   at Program.RunAction(Action`1 lambda, Object state) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 90
   at Program..ctor(Action action) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 58
   at Program..ctor() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 50
   at Program.Main(String[] args) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 15
```
Into
```
System.Exception: Collection was modified; enumeration operation may not execute. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at bool System.Collections.Generic.List<T>+Enumerator.MoveNextRare()
   at IEnumerable<string> Program.Iterator(int startAt)+MoveNext() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 65
   at bool System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.MoveNext()
   at string string.Join(string separator, IEnumerable<string> values)
   at string Program+GenericClass<TSuperType>.GenericMethod<TSubType>(ref TSubType value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 172
   --- End of inner exception stack trace ---
   at string Program+GenericClass<TSuperType>.GenericMethod<TSubType>(ref TSubType value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 176
   at async Task<string> Program.MethodAsync(int value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 78
   at async Task<string> Program.MethodAsync<TValue>(TValue value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 84
   at (string val, bool) Program.Method(string value)+()=>{} [0] in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 103
   at (string val, bool) Program.Method(string value)+()=>{} [1] in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 105
   at string Program.RunLambda(Func<string> lambda) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 97
   at (string val, bool) Program.Method(string value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 105
   at string Program.RefMethod(string value)+LocalFuncRefReturn() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 127
   at string Program.RefMethod(string value)+LocalFuncParam(string val) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 121
   at string Program.RefMethod(string value) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 117
   at (string val, bool) Program.s_func(string s, bool b) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 43
   at void Program.s_action(string s, bool b) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 42
   at void Program.Start((string val, bool) param) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 158
   at void Program.Start((string val, bool) param)+LocalFunc1(long l) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 139
   at void Program.Start((string val, bool) param)+LocalFunc2(bool b1, bool b2) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 144
   at string Program.Start() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 135
   at Program(Action action)+()=>{} in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 50
   at Program(Action action)+(object s)=>{} [1] in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 58
   at Program(Action action)+(Action<object> lambda, object state)=>{} in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 45
   at Program(Action action)+(object state)=>{} [0] in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 58
   at void Program.RunAction(Action<object> lambda, object state) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 90
   at new Program(Action action) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 58
   at new Program() in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 50
   at void Program.Main(string[] args) in C:\GitHub\Ben.Demystifier\sample\StackTrace\Program.cs:line 15
```

**Comment by Zoxive** [comment]
> API still needs some work

Dumb question.. theres an API?

I guess i was assuming exception.Demystify() returned an exception? Which on .ToString() returned your format. This would allow it to seamlessly work with any logging frameworks. etc

**Comment by benaadams** [comment]
> I guess i was assuming exception.Demystify() returned an exception?

Oooh... that could work...

**Comment by benaadams** [comment]
K, looks like I can rewrite the stack trace (string) inside the exception; and can then just pass around the original exception (type maintained). [nod to @enkafan]

**Comment by benaadams** [comment]
Code in repo and available via nuget https://github.com/benaadams/Ben.Demystifier/releases/tag/v0.0.1

**Comment by dennisdoomen** [comment]
Is it a source or a binary package?

**Comment by benaadams** [comment]
Binary; other issue is still open atm https://github.com/benaadams/Ben.Demystifier/issues/2 😄
